"""Canonical built-in menu catalog shared by installation and tenant provisioning."""

from app.core.id_generator import next_id
from app.modules.ai.constants import AI_CHAT_USE_PERMISSION, AI_FILE_PARSE_PERMISSION
from app.modules.system.constants import DEPT_MOVE_PERMISSION, USER_ROLE_AUTH_PERMISSION
from app.modules.system.models.menu import Menu

MENU_DEFINITIONS = [
    # ============ AI 助手 ============
    {
        "route_name": "ai_chat",
        "parent_route": "0",
        "menu_name": "AI 助手",
        "menu_type": "C",
        "icon": "carbon:chat-bot",
        "icon_type": "1",
        "component": "layout.base$view.ai_chat",
        "layout": "base",
        "page": "ai_chat",
        "route_path": "/ai/chat",
        "i18n_key": "route.ai_chat",
        "order": 0,
        "status": "1",
        "hide_in_menu": False,
        "keep_alive": False,
        "constant": False,
        "multi_tab": False,
    },
    # ============ AI 管理 ============
    {
        "route_name": "ai",
        "parent_route": "0",
        "menu_name": "AI 管理",
        "menu_type": "M",
        "icon": "ri:robot-2-line",
        "icon_type": "1",
        "component": "layout.base",
        "layout": "base",
        "route_path": "/ai",
        "i18n_key": "route.ai",
        "order": 1,
        "status": "1",
        "hide_in_menu": False,
        "keep_alive": False,
        "constant": False,
        "multi_tab": False,
    },
    {
        "key": "ai_chat_use",
        "parent_route": "ai_chat",
        "menu_name": "使用 AI 对话",
        "menu_type": "F",
        "permission": AI_CHAT_USE_PERMISSION,
        "route_path": "",
        "status": "1",
    },
    {
        "key": "ai_file_parse",
        "parent_route": "ai_chat",
        "menu_name": "解析聊天文件",
        "menu_type": "F",
        "permission": AI_FILE_PARSE_PERMISSION,
        "route_path": "",
        "status": "1",
    },
    # ============ 权限管理 ============
    {
        "route_name": "auth",
        "parent_route": "0",
        "menu_name": "权限管理",
        "menu_type": "M",
        "icon": "carbon:security",
        "icon_type": "1",
        "component": "layout.base",
        "layout": "base",
        "route_path": "/auth",
        "i18n_key": "route.auth",
        "order": 98,
        "status": "1",
        "hide_in_menu": False,
        "keep_alive": False,
        "constant": False,
        "multi_tab": False,
    },
    {
        "route_name": "system_dept",
        "parent_route": "auth",
        "menu_name": "部门管理",
        "menu_type": "C",
        "icon": "carbon:user-multiple",
        "icon_type": "1",
        "component": "view.system_dept",
        "page": "system_dept",
        "route_path": "/system/dept",
        "i18n_key": "route.system_dept",
        "order": 1,
        "status": "1",
        "hide_in_menu": False,
        "keep_alive": False,
        "constant": False,
        "multi_tab": False,
    },
    # ---- 部门管理按钮权限 ----
    {
        "key": "system_dept_list",
        "parent_route": "system_dept",
        "menu_name": "查询",
        "menu_type": "F",
        "permission": "system:dept:list",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_dept_add",
        "parent_route": "system_dept",
        "menu_name": "新增",
        "menu_type": "F",
        "permission": "system:dept:add",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_dept_edit",
        "parent_route": "system_dept",
        "menu_name": "修改",
        "menu_type": "F",
        "permission": "system:dept:edit",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_dept_move",
        "parent_route": "system_dept",
        "menu_name": "移动",
        "menu_type": "F",
        "permission": DEPT_MOVE_PERMISSION,
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_dept_delete",
        "parent_route": "system_dept",
        "menu_name": "删除",
        "menu_type": "F",
        "permission": "system:dept:delete",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_dept_batch-delete",
        "parent_route": "system_dept",
        "menu_name": "批量删除",
        "menu_type": "F",
        "permission": "system:dept:batch-delete",
        "route_path": "",
        "status": "1",
    },
    {
        "route_name": "system_user",
        "parent_route": "auth",
        "menu_name": "用户管理",
        "menu_type": "C",
        "icon": "carbon:user",
        "icon_type": "1",
        "component": "view.system_user",
        "page": "system_user",
        "route_path": "/system/user",
        "i18n_key": "route.system_user",
        "order": 2,
        "status": "1",
        "hide_in_menu": False,
        "keep_alive": False,
        "constant": False,
        "multi_tab": False,
    },
    # ---- 用户管理按钮权限 ----
    {
        "key": "system_user_list",
        "parent_route": "system_user",
        "menu_name": "查询",
        "menu_type": "F",
        "permission": "system:user:list",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_user_add",
        "parent_route": "system_user",
        "menu_name": "新增",
        "menu_type": "F",
        "permission": "system:user:add",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_user_edit",
        "parent_route": "system_user",
        "menu_name": "修改",
        "menu_type": "F",
        "permission": "system:user:edit",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_user_delete",
        "parent_route": "system_user",
        "menu_name": "删除",
        "menu_type": "F",
        "permission": "system:user:delete",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_user_batch-delete",
        "parent_route": "system_user",
        "menu_name": "批量删除",
        "menu_type": "F",
        "permission": "system:user:batch-delete",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_user_reset-password",
        "parent_route": "system_user",
        "menu_name": "重置密码",
        "menu_type": "F",
        "permission": "system:user:reset-password",
        "route_path": "",
        "status": "1",
    },
    # ---- 用户导入导出按钮权限 ----
    # 路由层 require_permissions("system:user:import" / "system:user:export") 依赖这两个 seed
    # 父菜单 system_user 已存在（line 238），sync_menus 按 permission 去重，重复执行安全。
    {
        "key": "system_user_import",
        "parent_route": "system_user",
        "menu_name": "导入",
        "menu_type": "F",
        "permission": "system:user:import",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_user_export",
        "parent_route": "system_user",
        "menu_name": "导出",
        "menu_type": "F",
        "permission": "system:user:export",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_user_role-auth",
        "parent_route": "system_user",
        "menu_name": "角色授权",
        "menu_type": "F",
        "permission": USER_ROLE_AUTH_PERMISSION,
        "route_path": "",
        "status": "1",
    },
    {
        "route_name": "system_role",
        "parent_route": "auth",
        "menu_name": "角色管理",
        "menu_type": "C",
        "icon": "carbon:user-role",
        "icon_type": "1",
        "component": "view.system_role",
        "page": "system_role",
        "route_path": "/system/role",
        "i18n_key": "route.system_role",
        "order": 3,
        "status": "1",
        "hide_in_menu": False,
        "keep_alive": False,
        "constant": False,
        "multi_tab": False,
    },
    # ---- 角色管理按钮权限 ----
    {
        "key": "system_role_list",
        "parent_route": "system_role",
        "menu_name": "查询",
        "menu_type": "F",
        "permission": "system:role:list",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_role_add",
        "parent_route": "system_role",
        "menu_name": "新增",
        "menu_type": "F",
        "permission": "system:role:add",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_role_edit",
        "parent_route": "system_role",
        "menu_name": "修改",
        "menu_type": "F",
        "permission": "system:role:edit",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_role_delete",
        "parent_route": "system_role",
        "menu_name": "删除",
        "menu_type": "F",
        "permission": "system:role:delete",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_role_batch-delete",
        "parent_route": "system_role",
        "menu_name": "批量删除",
        "menu_type": "F",
        "permission": "system:role:batch-delete",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_role_menu-auth",
        "parent_route": "system_role",
        "menu_name": "菜单权限",
        "menu_type": "F",
        "permission": "system:role:menu-auth",
        "route_path": "",
        "status": "1",
    },
    {
        "route_name": "system_menu",
        "parent_route": "auth",
        "menu_name": "菜单管理",
        "menu_type": "C",
        "icon": "carbon:menu",
        "icon_type": "1",
        "component": "view.system_menu",
        "page": "system_menu",
        "route_path": "/system/menu",
        "i18n_key": "route.system_menu",
        "order": 4,
        "status": "1",
        "hide_in_menu": False,
        "keep_alive": False,
        "constant": False,
        "multi_tab": False,
    },
    # ---- 菜单管理按钮权限 ----
    {
        "key": "system_menu_list",
        "parent_route": "system_menu",
        "menu_name": "查询",
        "menu_type": "F",
        "permission": "system:menu:list",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_menu_add",
        "parent_route": "system_menu",
        "menu_name": "新增",
        "menu_type": "F",
        "permission": "system:menu:add",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_menu_edit",
        "parent_route": "system_menu",
        "menu_name": "修改",
        "menu_type": "F",
        "permission": "system:menu:edit",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_menu_delete",
        "parent_route": "system_menu",
        "menu_name": "删除",
        "menu_type": "F",
        "permission": "system:menu:delete",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_menu_batch-delete",
        "parent_route": "system_menu",
        "menu_name": "批量删除",
        "menu_type": "F",
        "permission": "system:menu:batch-delete",
        "route_path": "",
        "status": "1",
    },
    # ============ 系统管理 ============
    {
        "route_name": "system",
        "parent_route": "0",
        "menu_name": "系统管理",
        "menu_type": "M",
        "icon": "carbon:cloud-service-management",
        "icon_type": "1",
        "component": "layout.base",
        "layout": "base",
        "route_path": "/system",
        "i18n_key": "route.system",
        "order": 99,
        "status": "1",
        "hide_in_menu": False,
        "keep_alive": False,
        "constant": False,
        "multi_tab": False,
    },
    {
        "route_name": "dashboard",
        "parent_route": "system",
        "menu_name": "仪表盘",
        "menu_type": "C",
        "icon": "carbon:dashboard",
        "icon_type": "1",
        "component": "view.dashboard",
        "page": "dashboard",
        "route_path": "/dashboard",
        "i18n_key": "route.dashboard",
        "order": 0,
        "status": "1",
        "hide_in_menu": False,
        "keep_alive": False,
        "constant": False,
        "multi_tab": False,
    },
    {
        "route_name": "system_dict",
        "parent_route": "system",
        "menu_name": "字典管理",
        "menu_type": "C",
        "icon": "fluent-mdl2:dictionary",
        "icon_type": "1",
        "component": "view.system_dict",
        "page": "system_dict",
        "route_path": "/system/dict",
        "i18n_key": "route.system_dict",
        "order": 1,
        "status": "1",
        "hide_in_menu": False,
        "keep_alive": False,
        "constant": False,
        "multi_tab": False,
    },
    # ---- 字典类型管理按钮权限 ----
    {
        "key": "system_dict-type_list",
        "parent_route": "system_dict",
        "menu_name": "查询",
        "menu_type": "F",
        "permission": "system:dict-type:list",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_dict-type_add",
        "parent_route": "system_dict",
        "menu_name": "新增",
        "menu_type": "F",
        "permission": "system:dict-type:add",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_dict-type_edit",
        "parent_route": "system_dict",
        "menu_name": "修改",
        "menu_type": "F",
        "permission": "system:dict-type:edit",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_dict-type_delete",
        "parent_route": "system_dict",
        "menu_name": "删除",
        "menu_type": "F",
        "permission": "system:dict-type:delete",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_dict-type_batch-delete",
        "parent_route": "system_dict",
        "menu_name": "批量删除",
        "menu_type": "F",
        "permission": "system:dict-type:batch-delete",
        "route_path": "",
        "status": "1",
    },
    {
        "route_name": "system_dict_data",
        "parent_route": "system",
        "menu_name": "字典数据",
        "menu_type": "C",
        "icon": "fluent-mdl2:dictionary",
        "icon_type": "1",
        "component": "view.system_dict_data",
        "page": "system_dict_data",
        "route_path": "/system/dict/data",
        "i18n_key": "route.system_dict_data",
        "order": 2,
        "status": "1",
        "hide_in_menu": True,
        "keep_alive": False,
        "constant": False,
        "multi_tab": False,
    },
    # ---- 字典数据管理按钮权限 ----
    {
        "key": "system_dict-data_list",
        "parent_route": "system_dict_data",
        "menu_name": "查询",
        "menu_type": "F",
        "permission": "system:dict-data:list",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_dict-data_add",
        "parent_route": "system_dict_data",
        "menu_name": "新增",
        "menu_type": "F",
        "permission": "system:dict-data:add",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_dict-data_edit",
        "parent_route": "system_dict_data",
        "menu_name": "修改",
        "menu_type": "F",
        "permission": "system:dict-data:edit",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_dict-data_delete",
        "parent_route": "system_dict_data",
        "menu_name": "删除",
        "menu_type": "F",
        "permission": "system:dict-data:delete",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_dict-data_batch-delete",
        "parent_route": "system_dict_data",
        "menu_name": "批量删除",
        "menu_type": "F",
        "permission": "system:dict-data:batch-delete",
        "route_path": "",
        "status": "1",
    },
    {
        "route_name": "system_file",
        "parent_route": "system",
        "menu_name": "文件管理",
        "menu_type": "C",
        "icon": "carbon:cloud-upload",
        "icon_type": "1",
        "component": "view.system_file",
        "page": "system_file",
        "route_path": "/system/file",
        "i18n_key": "route.system_file",
        "order": 3,
        "status": "1",
        "hide_in_menu": False,
        "keep_alive": False,
        "constant": False,
        "multi_tab": False,
    },
    # ---- 文件管理按钮权限 ----
    {
        "key": "system_file_list",
        "parent_route": "system_file",
        "menu_name": "查询",
        "menu_type": "F",
        "permission": "system:file:list",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_file_upload",
        "parent_route": "system_file",
        "menu_name": "上传",
        "menu_type": "F",
        "permission": "system:file:upload",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_file_delete",
        "parent_route": "system_file",
        "menu_name": "删除",
        "menu_type": "F",
        "permission": "system:file:delete",
        "route_path": "",
        "status": "1",
    },
    # ---- 系统设置：固定表单与独立权限 ----
    {
        "route_name": "system_setting",
        "parent_route": "system",
        "menu_name": "系统设置",
        "menu_type": "C",
        "icon": "carbon:settings",
        "icon_type": "1",
        "component": "view.system_setting",
        "page": "system_setting",
        "route_path": "/system/setting",
        "i18n_key": "route.system_setting",
        "order": 4,
        "status": "1",
        "hide_in_menu": False,
        "keep_alive": False,
        "constant": False,
        "multi_tab": False,
    },
    {
        "key": "system_setting_list",
        "parent_route": "system_setting",
        "menu_name": "查询",
        "menu_type": "F",
        "permission": "system:setting:list",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_setting_edit",
        "parent_route": "system_setting",
        "menu_name": "修改",
        "menu_type": "F",
        "permission": "system:setting:edit",
        "route_path": "",
        "status": "1",
    },
    # ---- 系统设置 ----
    {
        "route_name": "system_config",
        "parent_route": "system",
        "menu_name": "自定义参数",
        "menu_type": "C",
        "icon": "carbon:settings",
        "icon_type": "1",
        "component": "view.system_config",
        "page": "system_config",
        "route_path": "/system/config",
        "i18n_key": "route.system_config",
        "order": 5,
        "status": "1",
        "hide_in_menu": False,
        "keep_alive": False,
        "constant": False,
        "multi_tab": False,
    },
    # ---- 系统设置按钮权限 ----
    {
        "key": "system_config_list",
        "parent_route": "system_config",
        "menu_name": "查询",
        "menu_type": "F",
        "permission": "system:config:list",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_config_add",
        "parent_route": "system_config",
        "menu_name": "新增",
        "menu_type": "F",
        "permission": "system:config:add",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_config_edit",
        "parent_route": "system_config",
        "menu_name": "修改",
        "menu_type": "F",
        "permission": "system:config:edit",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_config_delete",
        "parent_route": "system_config",
        "menu_name": "删除",
        "menu_type": "F",
        "permission": "system:config:delete",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_config_batch-delete",
        "parent_route": "system_config",
        "menu_name": "批量删除",
        "menu_type": "F",
        "permission": "system:config:batch-delete",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_config_export",
        "parent_route": "system_config",
        "menu_name": "导出",
        "menu_type": "F",
        "permission": "system:config:export",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_config_import",
        "parent_route": "system_config",
        "menu_name": "导入",
        "menu_type": "F",
        "permission": "system:config:import",
        "route_path": "",
        "status": "1",
    },
    # ---- 数据权限演示 ----
    # route_name 和 i18n_key 用 kebab-case 匹配前端 @elegant-router 生成的命名
    # （目录 data-scope-demo/index.vue → route name 'system_data-scope-demo'）
    {
        "route_name": "system_data-scope-demo",
        "parent_route": "system",
        "menu_name": "数据权限演示",
        "menu_type": "C",
        "icon": "carbon:security",
        "icon_type": "1",
        "component": "view.system_data-scope-demo",
        "page": "system_data-scope-demo",
        "route_path": "/system/data-scope-demo",
        "i18n_key": "route.system_data-scope-demo",
        "order": 8,
        "status": "1",
        "hide_in_menu": False,
        "keep_alive": False,
        "constant": False,
        "multi_tab": False,
    },
    # ---- 数据权限演示按钮权限 ----
    {
        "key": "system_data-scope-demo_list",
        "parent_route": "system_data-scope-demo",
        "menu_name": "查询",
        "menu_type": "F",
        "permission": "system:data-scope-demo:list",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_data-scope-demo_add",
        "parent_route": "system_data-scope-demo",
        "menu_name": "新增",
        "menu_type": "F",
        "permission": "system:data-scope-demo:add",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_data-scope-demo_edit",
        "parent_route": "system_data-scope-demo",
        "menu_name": "修改",
        "menu_type": "F",
        "permission": "system:data-scope-demo:edit",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_data-scope-demo_delete",
        "parent_route": "system_data-scope-demo",
        "menu_name": "删除",
        "menu_type": "F",
        "permission": "system:data-scope-demo:delete",
        "route_path": "",
        "status": "1",
    },
    # ---- 监控管理 ----
    {
        "route_name": "system_monitor",
        "parent_route": "system",
        "menu_name": "监控管理",
        "menu_type": "M",
        "icon": "carbon:activity",
        "icon_type": "1",
        "component": "layout.base",
        "layout": "base",
        "route_path": "/system/monitor",
        "i18n_key": "route.system_monitor",
        "order": 5,
        "status": "1",
        "hide_in_menu": True,
        "keep_alive": False,
        "constant": False,
        "multi_tab": False,
    },
    {
        "route_name": "system_operation-log",
        "parent_route": "system",
        "menu_name": "操作日志",
        "menu_type": "C",
        "icon": "carbon:document",
        "icon_type": "1",
        "component": "view.system_operation-log",
        "page": "system_operation-log",
        "route_path": "/system/operation-log",
        "i18n_key": "route.system_operation-log",
        "order": 6,
        "status": "1",
        "hide_in_menu": False,
        "keep_alive": False,
        "constant": False,
        "multi_tab": False,
    },
    # ---- 操作日志按钮权限 ----
    {
        "key": "monitor_operation-log_list",
        "parent_route": "system_operation-log",
        "menu_name": "查询",
        "menu_type": "F",
        "permission": "monitor:operation-log:list",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "monitor_operation-log_clean",
        "parent_route": "system_operation-log",
        "menu_name": "清理",
        "menu_type": "F",
        "permission": "monitor:operation-log:clean",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "monitor_operation-log_delete",
        "parent_route": "system_operation-log",
        "menu_name": "批量删除",
        "menu_type": "F",
        "permission": "monitor:operation-log:delete",
        "route_path": "",
        "status": "1",
    },
    {
        "route_name": "system_login-log",
        "parent_route": "system",
        "menu_name": "登录日志",
        "menu_type": "C",
        "icon": "carbon:login",
        "icon_type": "1",
        "component": "view.system_login-log",
        "page": "system_login-log",
        "route_path": "/system/login-log",
        "i18n_key": "route.system_login-log",
        "order": 7,
        "status": "1",
        "hide_in_menu": False,
        "keep_alive": False,
        "constant": False,
        "multi_tab": False,
    },
    # ---- 登录日志按钮权限 ----
    {
        "key": "monitor_login-log_list",
        "parent_route": "system_login-log",
        "menu_name": "查询",
        "menu_type": "F",
        "permission": "monitor:login-log:list",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "monitor_login-log_clean",
        "parent_route": "system_login-log",
        "menu_name": "清理",
        "menu_type": "F",
        "permission": "monitor:login-log:clean",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "monitor_login-log_delete",
        "parent_route": "system_login-log",
        "menu_name": "批量删除",
        "menu_type": "F",
        "permission": "monitor:login-log:delete",
        "route_path": "",
        "status": "1",
    },
    # ============ 任务中心 ============
    {
        "route_name": "task",
        "parent_route": "0",
        "menu_name": "任务中心",
        "menu_type": "M",
        "icon": "carbon:task",
        "icon_type": "1",
        "component": "layout.base",
        "layout": "base",
        "route_path": "/task",
        "i18n_key": "route.task",
        "order": 100,
        "status": "1",
        "hide_in_menu": False,
        "keep_alive": False,
        "constant": False,
        "multi_tab": False,
    },
    {
        "route_name": "system_job",
        "parent_route": "task",
        "menu_name": "定时任务",
        "menu_type": "C",
        "icon": "carbon:timer",
        "icon_type": "1",
        "component": "view.system_job",
        "page": "system_job",
        "route_path": "/system/job",
        "i18n_key": "route.system_job",
        "order": 1,
        "status": "1",
        "hide_in_menu": False,
        "keep_alive": False,
        "constant": False,
        "multi_tab": False,
    },
    # ---- 定时任务管理按钮权限 ----
    {
        "key": "system_job_list",
        "parent_route": "system_job",
        "menu_name": "查询",
        "menu_type": "F",
        "permission": "system:job:list",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_job_add",
        "parent_route": "system_job",
        "menu_name": "新增",
        "menu_type": "F",
        "permission": "system:job:add",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_job_edit",
        "parent_route": "system_job",
        "menu_name": "修改",
        "menu_type": "F",
        "permission": "system:job:edit",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_job_delete",
        "parent_route": "system_job",
        "menu_name": "删除",
        "menu_type": "F",
        "permission": "system:job:delete",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_job_batch-delete",
        "parent_route": "system_job",
        "menu_name": "批量删除",
        "menu_type": "F",
        "permission": "system:job:batch-delete",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_job_run",
        "parent_route": "system_job",
        "menu_name": "立即执行",
        "menu_type": "F",
        "permission": "system:job:run",
        "route_path": "",
        "status": "1",
    },
    {
        "route_name": "system_job-log",
        "parent_route": "task",
        "menu_name": "任务日志",
        "menu_type": "C",
        "icon": "carbon:document-tasks",
        "icon_type": "1",
        "component": "view.system_job-log",
        "page": "system_job-log",
        "route_path": "/system/job-log",
        "i18n_key": "route.system_job-log",
        "order": 2,
        "status": "1",
        "hide_in_menu": False,
        "keep_alive": False,
        "constant": False,
        "multi_tab": False,
    },
    # ---- 任务日志按钮权限 ----
    {
        "key": "system_job-log_list",
        "parent_route": "system_job-log",
        "menu_name": "查询",
        "menu_type": "F",
        "permission": "system:job-log:list",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_job-log_clean",
        "parent_route": "system_job-log",
        "menu_name": "清理",
        "menu_type": "F",
        "permission": "system:job-log:clean",
        "route_path": "",
        "status": "1",
    },
    {
        "key": "system_job-log_batch-delete",
        "parent_route": "system_job-log",
        "menu_name": "批量删除",
        "menu_type": "F",
        "permission": "system:job-log:batch-delete",
        "route_path": "",
        "status": "1",
    },
    # ============ 应用市场 ============
    {
        "route_name": "marketplace",
        "parent_route": "0",
        "menu_name": "应用市场",
        "menu_type": "C",
        "icon": "carbon:store",
        "icon_type": "1",
        "component": "layout.base$view.marketplace",
        "layout": "base",
        "page": "marketplace",
        "route_path": "/marketplace",
        "i18n_key": "route.marketplace",
        "order": 50,
        "status": "1",
        "hide_in_menu": False,
        "keep_alive": False,
        "constant": False,
        "multi_tab": False,
    },
    # ---- 应用详情（隐藏页，点卡片进入）----
    {
        "route_name": "marketplace-detail",
        "parent_route": "0",
        "menu_name": "应用详情",
        "menu_type": "C",
        "icon": "carbon:store",
        "icon_type": "1",
        "component": "layout.base$view.marketplace-detail",
        "layout": "base",
        "page": "marketplace-detail",
        "route_path": "/marketplace/detail",
        "i18n_key": "route.marketplace-detail",
        "order": 51,
        "status": "1",
        "hide_in_menu": True,
        "keep_alive": False,
        "constant": False,
        "multi_tab": False,
    },
    # ============ 应用管理（目录）============
    {
        "route_name": "app-management",
        "parent_route": "0",
        "menu_name": "应用管理",
        "menu_type": "M",
        "icon": "carbon:cloud-services",
        "icon_type": "1",
        "component": "layout.base",
        "layout": "base",
        "route_path": "/marketplace",
        "i18n_key": "route.app-management",
        "order": 52,
        "status": "1",
        "hide_in_menu": False,
        "keep_alive": False,
        "constant": False,
        "multi_tab": False,
    },
    {
        "route_name": "marketplace_installed",
        "parent_route": "app-management",
        "menu_name": "已安装应用",
        "menu_type": "C",
        "icon": "carbon:cloud-download",
        "icon_type": "1",
        # 子菜单 route_name 用下划线 → transform 走 isView 路径
        # component 用连字符 → 匹配 @elegant-router imports.ts 的 key
        "component": "view.marketplace-installed",
        "page": "marketplace-installed",
        "route_path": "/marketplace/installed",
        "i18n_key": "route.marketplace-installed",
        "order": 1,
        "status": "1",
        "hide_in_menu": False,
        "keep_alive": False,
        "constant": False,
        "multi_tab": False,
    },
    # ---- 已安装应用按钮权限（安装/卸载/启用/停用） ----
    {
        "key": "marketplace_install",
        "parent_route": "marketplace_installed",
        "menu_name": "安装/卸载/启停",
        "menu_type": "F",
        "permission": "marketplace:install",
        "route_path": "",
        "status": "1",
    },
    {
        "route_name": "marketplace_upload",
        "parent_route": "app-management",
        "menu_name": "上传应用",
        "menu_type": "C",
        "icon": "carbon:upload",
        "icon_type": "1",
        "component": "view.marketplace-upload",
        "page": "marketplace-upload",
        "route_path": "/marketplace/upload",
        "i18n_key": "route.marketplace-upload",
        "order": 2,
        "status": "1",
        "hide_in_menu": False,
        "keep_alive": False,
        "constant": False,
        "multi_tab": False,
    },
    {
        # 应用审核（仅 marketplace:review 权限可见）
        # 云端与本地拆分后归入 cloud-only 菜单。
        "route_name": "marketplace_review",
        "parent_route": "app-management",
        "menu_name": "应用审核",
        "menu_type": "C",
        "icon": "carbon:task-approved",
        "icon_type": "1",
        "component": "view.marketplace-review",
        "page": "marketplace-review",
        "route_path": "/marketplace/review",
        "i18n_key": "route.marketplace-review",
        "order": 3,
        "status": "1",
        "hide_in_menu": False,
        "keep_alive": False,
        "constant": False,
        "multi_tab": False,
    },
    # ---- 应用审核按钮权限（批准/拒绝） ----
    {
        "key": "marketplace_review_btn",
        "parent_route": "marketplace_review",
        "menu_name": "审核",
        "menu_type": "F",
        "permission": "marketplace:review",
        "route_path": "",
        "status": "1",
    },
    # ---- AI Trace audit page, independent from ai:agent:* ----
    {
        "route_name": "ai_trace",
        "parent_route": "ai",
        "menu_name": "AI Trace 查看",
        "menu_type": "C",
        "permission": "ai:trace:view",
        "icon": "carbon:flow-logs-vpc",
        "icon_type": "1",
        "component": "view.ai_trace",
        "page": "ai_trace",
        "route_path": "/ai/trace",
        "i18n_key": "route.ai_trace",
        "order": 4,
        "status": "1",
        "hide_in_menu": False,
        "keep_alive": False,
        "constant": False,
        "multi_tab": False,
    },
    # ---- AI 路由反馈 ----
    # route_name / component / page / i18n_key 用 kebab-case 匹配前端 @elegant-router 命名约定
    # （view.ai_routing-feedback 对应 src/views/ai/routing-feedback/index.vue；下划线形式会被
    # transformElegantRouteToVueRoute 视为查不到 view 而抛 "View component not found"，路由被静默丢弃）
    {
        "route_name": "ai_routing-feedback",
        "parent_route": "ai",
        "menu_name": "AI 路由反馈",
        "menu_type": "C",
        "icon": "carbon:analytics",
        "icon_type": "1",
        "component": "view.ai_routing-feedback",
        "page": "ai_routing-feedback",
        "route_path": "/ai/routing-feedback",
        "i18n_key": "route.ai_routing-feedback",
        "order": 5,
        "status": "1",
        "hide_in_menu": False,
        "keep_alive": False,
        "constant": False,
        "multi_tab": False,
    },
    # ---- AI 路由反馈按钮权限 ----
    {
        "key": "ai_routing_feedback_list",
        "parent_route": "ai_routing-feedback",
        "menu_name": "查询",
        "menu_type": "F",
        "permission": "ai:routing-feedback:list",
        "route_path": "",
        "status": "1",
    },
    # ---- 角色 AI Agent 授权按钮权限 ----
    {
        "key": "system_role_ai_agent_auth",
        "parent_route": "system_role",
        "menu_name": "AI Agent 授权",
        "menu_type": "F",
        "permission": "system:role:ai-agent-auth",
        "route_path": "",
        "status": "1",
    },
]


def menu_values(definition: dict) -> dict:
    """Translate logical definitions without copying their deployment-only keys."""
    values = {
        key: value
        for key, value in definition.items()
        if key not in {"key", "parent_route"}
    }
    if values["menu_type"] == "F":
        values["route_name"] = None
        values["i18n_key"] = "builtin.permission." + values["permission"].replace(
            ":", "_"
        ).replace("-", "_")
    for key in ("hide_in_menu", "keep_alive", "constant", "multi_tab"):
        values.setdefault(key, False)
    values.setdefault("order", 0)
    values.setdefault("status", "1")
    return values


def build_initial_menus(*, tenant_id: int, definitions=None) -> list[Menu]:
    """Create fresh objects and IDs on each invocation, in parent-first order."""
    definitions = MENU_DEFINITIONS if definitions is None else definitions
    ids = {d["route_name"]: next_id() for d in definitions if d["menu_type"] != "F"}
    menus = []
    for d in definitions:
        parent = d["parent_route"]
        menus.append(
            Menu(
                tenant_id=tenant_id,
                menu_id=next_id() if d["menu_type"] == "F" else ids[d["route_name"]],
                parent_id=None if parent == "0" else ids[parent],
                **menu_values(d),
            )
        )
    # A fresh database must flush parents before their children.
    ordered = []
    pending = menus[:]
    resolved = set()
    while pending:
        ready = [m for m in pending if m.parent_id is None or m.parent_id in resolved]
        if not ready:
            raise ValueError("menu catalog contains an unresolved parent")
        ordered.extend(ready)
        resolved.update(m.menu_id for m in ready)
        pending = [m for m in pending if m not in ready]
    return ordered
