"""add operation log and login log tables

Revision ID: 0d45e1d2870d
Revises: a6a5322fd1b6
Create Date: 2026-05-16 15:53:16.818700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d45e1d2870d'
down_revision: Union[str, Sequence[str], None] = 'a6a5322fd1b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_login_log',
    sa.Column('login_log_id', sa.BigInteger(), nullable=False, comment='日志ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='登录用户ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='登录用户名'),
    sa.Column('ip', sa.String(length=50), nullable=True, comment='登录IP'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='浏览器信息'),
    sa.Column('status', sa.String(length=2), nullable=False, comment='状态：1-成功，2-失败，3-锁定'),
    sa.Column('message', sa.String(length=200), nullable=True, comment='结果描述'),
    sa.Column('login_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='登录时间'),
    sa.PrimaryKeyConstraint('login_log_id')
    )
    op.create_index('ix_login_log_login_time', 'sys_login_log', ['login_time'], unique=False)
    op.create_table('sys_operation_log',
    sa.Column('operation_log_id', sa.BigInteger(), nullable=False, comment='日志ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='操作人ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='操作人用户名'),
    sa.Column('module', sa.String(length=50), nullable=False, comment='业务模块'),
    sa.Column('action', sa.String(length=20), nullable=False, comment='操作类型'),
    sa.Column('method', sa.String(length=10), nullable=False, comment='HTTP方法'),
    sa.Column('path', sa.String(length=200), nullable=False, comment='请求路径'),
    sa.Column('request_params', sa.Text(), nullable=True, comment='请求参数摘要'),
    sa.Column('status_code', sa.Integer(), nullable=True, comment='响应状态码'),
    sa.Column('ip', sa.String(length=50), nullable=True, comment='操作者IP'),
    sa.Column('duration', sa.Integer(), nullable=True, comment='耗时（毫秒）'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='操作时间'),
    sa.PrimaryKeyConstraint('operation_log_id')
    )
    op.create_index('ix_operation_log_create_time', 'sys_operation_log', ['create_time'], unique=False)
    op.create_index('ix_operation_log_user_id', 'sys_operation_log', ['user_id'], unique=False)
    op.alter_column('sys_config', 'config_name',
               existing_type=sa.VARCHAR(length=100),
               comment='配置名称',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('sys_config', 'config_type',
               existing_type=sa.VARCHAR(length=20),
               comment='配置类型：text/richtext/file',
               existing_nullable=False,
               existing_server_default=sa.text("'text'::character varying"))
    op.alter_column('sys_config', 'is_public',
               existing_type=sa.BOOLEAN(),
               comment='是否公开访问',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sys_config', 'is_public',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否公开访问',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('sys_config', 'config_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='配置类型：text/richtext/file',
               existing_nullable=False,
               existing_server_default=sa.text("'text'::character varying"))
    op.alter_column('sys_config', 'config_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='配置名称',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.drop_index('ix_operation_log_user_id', table_name='sys_operation_log')
    op.drop_index('ix_operation_log_create_time', table_name='sys_operation_log')
    op.drop_table('sys_operation_log')
    op.drop_index('ix_login_log_login_time', table_name='sys_login_log')
    op.drop_table('sys_login_log')
    # ### end Alembic commands ###
