"""create marketplace tables

Revision ID: 47538f0c11ae
Revises: b3c4d5e6f7a8
Create Date: 2026-06-17 10:06:27.824975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47538f0c11ae'
down_revision: Union[str, Sequence[str], None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mk_app',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='应用ID'),
    sa.Column('tenant_id', sa.BigInteger(), server_default='0', nullable=False, comment='租户ID（Phase 1 单租户默认 0，强制过滤）'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='应用名称'),
    sa.Column('slug', sa.String(length=150), nullable=False, comment='URL slug（唯一）'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='应用类型: lowcode|frontend|backend|fullstack|theme|bundle'),
    sa.Column('category', sa.String(length=30), nullable=False, comment='应用分类'),
    sa.Column('description', sa.Text(), nullable=True, comment='应用描述'),
    sa.Column('icon', sa.String(length=500), nullable=True, comment='图标 URL（对象存储，禁止外链）'),
    sa.Column('author_id', sa.BigInteger(), nullable=True, comment='作者用户ID'),
    sa.Column('author_name', sa.String(length=100), nullable=True, comment='作者名（冗余展示字段）'),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False, comment='状态: draft|published|...'),
    sa.Column('current_version_id', sa.BigInteger(), nullable=True, comment='当前发布版本ID'),
    sa.Column('homepage', sa.String(length=500), nullable=True, comment='主页 URL'),
    sa.Column('license', sa.String(length=50), nullable=True, comment='开源协议'),
    sa.Column('download_count', sa.Integer(), server_default='0', nullable=False, comment='累计下载次数'),
    sa.Column('avg_rating', sa.Numeric(precision=3, scale=1), server_default='0.0', nullable=False, comment='平均评分（0-5）'),
    sa.Column('rating_count', sa.Integer(), server_default='0', nullable=False, comment='评分人数'),
    sa.Column('tags_text', sa.Text(), nullable=True, comment='冗余：mk_app_tag 名称以空格拼接，用于 search_vector'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint('avg_rating >= 0 AND avg_rating <= 5', name='ck_mk_app_avg_rating_range'),
    sa.ForeignKeyConstraint(['author_id'], ['sys_user.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_mk_app_status_category', 'mk_app', ['status', 'category'], unique=False)
    op.create_table('mk_app_version',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='版本ID'),
    sa.Column('app_id', sa.BigInteger(), nullable=False, comment='所属应用ID'),
    sa.Column('version', sa.String(length=20), nullable=False, comment='语义化版本号（semver）'),
    sa.Column('changelog', sa.Text(), nullable=True, comment='变更说明'),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='应用清单（JSON）'),
    sa.Column('file_url', sa.String(length=500), nullable=False, comment='制品包 URL'),
    sa.Column('file_hash', sa.String(length=64), nullable=False, comment='制品包 SHA-256'),
    sa.Column('file_size', sa.BigInteger(), nullable=True, comment='制品包大小（字节）'),
    sa.Column('review_status', sa.String(length=20), server_default='pending', nullable=False, comment='审核状态: pending|approved|rejected'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['app_id'], ['mk_app.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'version', name='uq_mk_app_version_app_version'),
    comment='应用版本（每次发布一行）'
    )
    op.create_index('ix_mk_app_version_app_created', 'mk_app_version', ['app_id', 'created_at'], unique=False)
    # Add mk_app.current_version_id FK after mk_app_version exists (circular dependency)
    op.create_foreign_key(
        'fk_mk_app_current_version_id_mk_app_version',
        'mk_app',
        'mk_app_version',
        ['current_version_id'],
        ['id'],
    )
    op.create_table('mk_app_permission',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='权限ID'),
    sa.Column('app_id', sa.BigInteger(), nullable=False, comment='所属应用ID'),
    sa.Column('type', sa.String(length=30), nullable=False, comment='权限类型: api|external_api|menu|db_table|...'),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='权限详情（原始结构）'),
    sa.Column('detail_hash', sa.String(length=64), nullable=False, comment='detail canonical JSON 的 SHA-256'),
    sa.Column('detail_canonical', sa.Text(), nullable=False, comment='审计字段：canonical JSON 文本，便于 hash 算法迁移'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['app_id'], ['mk_app.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'type', 'detail_hash', name='uq_mk_app_permission_app_type_hash')
    )
    op.create_index('ix_mk_app_permission_app_type', 'mk_app_permission', ['app_id', 'type'], unique=False)
    op.create_table('mk_app_rating',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='评分ID'),
    sa.Column('app_id', sa.BigInteger(), nullable=False, comment='被评分应用ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='评分用户ID'),
    sa.Column('rating', sa.SmallInteger(), nullable=False, comment='评分（1-5）'),
    sa.Column('comment', sa.Text(), nullable=True, comment='评分评论'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_mk_app_rating_range'),
    sa.ForeignKeyConstraint(['app_id'], ['mk_app.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'user_id', name='uq_mk_app_rating_app_user')
    )
    op.create_index('ix_mk_app_rating_app', 'mk_app_rating', ['app_id'], unique=False)
    op.create_table('mk_app_review',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='审核记录ID'),
    sa.Column('app_id', sa.BigInteger(), nullable=False, comment='所属应用ID'),
    sa.Column('version_id', sa.BigInteger(), nullable=False, comment='被审核版本ID'),
    sa.Column('rule_check_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='规则引擎检查结果'),
    sa.Column('rule_check_at', sa.DateTime(timezone=True), nullable=True, comment='规则检查完成时间'),
    sa.Column('ai_risk_level', sa.String(length=10), nullable=True, comment='AI 风险等级: low|medium|high'),
    sa.Column('ai_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='AI 审核报告'),
    sa.Column('ai_review_at', sa.DateTime(timezone=True), nullable=True, comment='AI 审核完成时间'),
    sa.Column('human_status', sa.String(length=20), server_default='pending', nullable=False, comment='人工审核状态: pending|approved|rejected'),
    sa.Column('human_reviewer_id', sa.BigInteger(), nullable=True, comment='人工审核人ID'),
    sa.Column('human_comment', sa.Text(), nullable=True, comment='人工审核意见'),
    sa.Column('human_reviewed_at', sa.DateTime(timezone=True), nullable=True, comment='人工审核完成时间'),
    sa.Column('final_status', sa.String(length=20), server_default='pending', nullable=False, comment='最终审核状态: pending|approved|rejected'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['app_id'], ['mk_app.id'], ),
    sa.ForeignKeyConstraint(['human_reviewer_id'], ['sys_user.user_id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['mk_app_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mk_app_review_app_version', 'mk_app_review', ['app_id', 'version_id'], unique=False)
    op.create_table('mk_tenant_app',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='安装记录ID'),
    sa.Column('tenant_id', sa.BigInteger(), server_default='0', nullable=False, comment='租户ID（Phase 1 单租户默认 0）'),
    sa.Column('app_id', sa.BigInteger(), nullable=False, comment='已安装应用ID'),
    sa.Column('installed_version', sa.String(length=20), nullable=False, comment='已安装版本号（semver 字符串）'),
    sa.Column('status', sa.String(length=20), server_default='installed', nullable=False, comment='安装状态: installed|disabled|uninstalled'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='安装配置（用户填写的）'),
    sa.Column('approved_permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='用户已批准的权限清单'),
    sa.Column('retained_table_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='卸载后保留的数据表名清单'),
    sa.Column('has_data', sa.Boolean(), server_default='false', nullable=False, comment='是否存在业务数据（决定是否可硬删除）'),
    sa.Column('installed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='首次安装时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['app_id'], ['mk_app.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'app_id', name='uq_mk_tenant_app_tenant_app')
    )
    op.create_index('ix_mk_tenant_app_tenant_status', 'mk_tenant_app', ['tenant_id', 'status'], unique=False)
    # NOTE: Alembic also detected a spurious ai_model drop/recreate — excluded because
    # ai_model is unrelated to this migration. The DB/model drift for ai_model should
    # be reconciled separately (AiModel is no longer imported in alembic/env.py).
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mk_tenant_app_tenant_status', table_name='mk_tenant_app')
    op.drop_table('mk_tenant_app')
    op.drop_index('ix_mk_app_review_app_version', table_name='mk_app_review')
    op.drop_table('mk_app_review')
    op.drop_index('ix_mk_app_rating_app', table_name='mk_app_rating')
    op.drop_table('mk_app_rating')
    op.drop_index('ix_mk_app_permission_app_type', table_name='mk_app_permission')
    op.drop_table('mk_app_permission')
    # Drop mk_app.current_version_id FK before dropping mk_app_version
    op.drop_constraint(
        'fk_mk_app_current_version_id_mk_app_version', 'mk_app', type_='foreignkey'
    )
    op.drop_index('ix_mk_app_version_app_created', table_name='mk_app_version')
    op.drop_table('mk_app_version')
    op.drop_index('ix_mk_app_status_category', table_name='mk_app')
    op.drop_table('mk_app')
    # ### end Alembic commands ###
