"""add file upload table

Revision ID: 6565b01411c3
Revises: 7035c014fc57
Create Date: 2026-04-20 10:51:07.887077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6565b01411c3'
down_revision: Union[str, Sequence[str], None] = '7035c014fc57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_file',
    sa.Column('file_id', sa.BigInteger(), nullable=False, comment='文件ID'),
    sa.Column('original_name', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='存储文件名(Snowflake ID)'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='相对路径'),
    sa.Column('file_url', sa.String(length=500), nullable=False, comment='文件访问URL'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='文件大小(字节)'),
    sa.Column('file_ext', sa.String(length=20), nullable=False, comment='文件扩展名'),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment='MIME类型'),
    sa.Column('business_type', sa.String(length=50), nullable=True, comment='业务类型(如product、avatar)'),
    sa.Column('business_id', sa.BigInteger(), nullable=True, comment='业务记录ID'),
    sa.Column('del_flag', sa.String(length=1), nullable=False, comment='删除标记: 0-正常, 1-已删除'),
    sa.Column('create_by', sa.String(length=64), nullable=True, comment='上传者'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='上传时间'),
    sa.PrimaryKeyConstraint('file_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_file')
    # ### end Alembic commands ###
