"""add_data_scope

Revision ID: 6957ad20070b
Revises: ef3d6a37d688
Create Date: 2026-04-29 09:22:35.815969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6957ad20070b'
down_revision: Union[str, Sequence[str], None] = 'ef3d6a37d688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_role_dept',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('dept_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['sys_dept.dept_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.role_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'dept_id')
    )
    op.add_column('sys_role', sa.Column('data_scope', sa.String(length=2), nullable=False, server_default='1', comment='数据权限范围：1-全部，2-自定义，3-本部门，4-本部门及以下，5-仅本人'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sys_role', 'data_scope')
    op.drop_table('sys_role_dept')
    # ### end Alembic commands ###
