# ruff: noqa: T201

"""init database

Revision ID: 7035c014fc57
Revises: 
Create Date: 2026-04-08 13:47:29.655663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7035c014fc57'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_dept',
    sa.Column('dept_id', sa.BigInteger(), nullable=False, comment='部门ID'),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='父部门ID'),
    sa.Column('ancestors', sa.String(length=500), nullable=True, comment='祖先路径'),
    sa.Column('dept_name', sa.String(length=100), nullable=False, comment='部门名称'),
    sa.Column('order_num', sa.Integer(), nullable=False, comment='显示顺序'),
    sa.Column('leader', sa.String(length=50), nullable=True, comment='负责人'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('status', sa.String(length=2), nullable=False, comment='状态：1-启用，2-禁用'),
    sa.Column('create_by', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('dept_id')
    )
    op.create_table('sys_dict_data',
    sa.Column('dict_code', sa.BigInteger(), nullable=False, comment='字典编码'),
    sa.Column('dict_sort', sa.Integer(), nullable=False, comment='字典排序'),
    sa.Column('dict_label', sa.String(length=100), nullable=False, comment='字典标签'),
    sa.Column('dict_value', sa.String(length=100), nullable=False, comment='字典键值'),
    sa.Column('dict_type', sa.String(length=100), nullable=False, comment='字典类型'),
    sa.Column('css_class', sa.String(length=100), nullable=True, comment='样式属性'),
    sa.Column('list_class', sa.String(length=100), nullable=True, comment='表格回显样式'),
    sa.Column('is_default', sa.String(length=2), nullable=False, comment='是否默认：Y-是，N-否'),
    sa.Column('status', sa.String(length=2), nullable=False, comment='状态：1-启用，2-禁用'),
    sa.Column('create_by', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('dict_code')
    )
    op.create_table('sys_dict_type',
    sa.Column('dict_type_id', sa.BigInteger(), nullable=False, comment='字典类型ID'),
    sa.Column('dict_name', sa.String(length=100), nullable=False, comment='字典名称'),
    sa.Column('dict_type', sa.String(length=100), nullable=False, comment='字典类型'),
    sa.Column('status', sa.String(length=2), nullable=False, comment='状态：1-启用，2-禁用'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('create_by', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('dict_type_id'),
    sa.UniqueConstraint('dict_name'),
    sa.UniqueConstraint('dict_type')
    )
    op.create_table('sys_menu',
    sa.Column('menu_id', sa.BigInteger(), nullable=False, comment='菜单ID'),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='父菜单ID'),
    sa.Column('menu_name', sa.String(length=50), nullable=False, comment='菜单标题'),
    sa.Column('menu_type', sa.String(length=1), nullable=False, comment='类型: M目录, C菜单, F按钮'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='菜单图标'),
    sa.Column('icon_type', sa.String(length=1), nullable=True, comment='菜单图标类型'),
    sa.Column('path', sa.String(length=255), nullable=True, comment='路由路径'),
    sa.Column('component', sa.String(length=255), nullable=True, comment='组件'),
    sa.Column('route_name', sa.String(length=50), nullable=True, comment='前端路由名称（name）'),
    sa.Column('route_path', sa.String(length=255), nullable=True, comment='前端路由路径'),
    sa.Column('order', sa.Integer(), nullable=False, comment='排序（越小越靠前）'),
    sa.Column('status', sa.String(length=2), nullable=False, comment='状态：1-启用，2-禁用'),
    sa.Column('create_by', sa.String(length=32), nullable=True, comment='创建人'),
    sa.Column('update_by', sa.String(length=32), nullable=True, comment='更新人'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('path_param', sa.String(length=255), nullable=True, comment='路径参数'),
    sa.Column('page', sa.String(length=255), nullable=True, comment='页面组件'),
    sa.Column('layout', sa.String(length=255), nullable=True, comment='布局组件'),
    sa.Column('i18n_key', sa.String(length=100), nullable=True, comment='国际化key'),
    sa.Column('keep_alive', sa.Boolean(), nullable=True, comment='缓存路由'),
    sa.Column('constant', sa.Boolean(), nullable=True, comment='常量路由'),
    sa.Column('href', sa.String(length=255), nullable=True, comment='外链'),
    sa.Column('hide_in_menu', sa.Boolean(), nullable=True, comment='隐藏菜单'),
    sa.Column('active_menu', sa.String(length=50), nullable=True, comment='激活菜单的路由名称'),
    sa.Column('multi_tab', sa.Boolean(), nullable=True, comment='是否支持多页签'),
    sa.Column('fixed_index_in_tab', sa.Integer(), nullable=True, comment='页签固定索引'),
    sa.Column('permission', sa.String(length=50), nullable=True, comment='按钮/功能权限'),
    sa.Column('query', sa.JSON(), nullable=True, comment='路由参数'),
    sa.PrimaryKeyConstraint('menu_id')
    )
    op.create_table('sys_role',
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.Column('role_name', sa.String(length=50), nullable=False, comment='角色名称'),
    sa.Column('role_code', sa.String(length=50), nullable=False, comment='角色编码'),
    sa.Column('role_desc', sa.String(length=255), nullable=True, comment='角色描述'),
    sa.Column('status', sa.String(length=2), nullable=False, comment='状态：1-启用，2-禁用'),
    sa.Column('create_by', sa.String(length=32), nullable=True, comment='创建人'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), nullable=True, comment='更新人'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_code'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('sys_user',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('user_name', sa.String(length=50), nullable=False, comment='账号'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='加密密码'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='状态'),
    sa.Column('user_avatar', sa.String(length=255), nullable=True, comment='头像地址'),
    sa.Column('user_email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('user_phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('user_gender', sa.String(length=1), nullable=True, comment='用户性别: 0:未知,1:男,2:女'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_sys_user_user_name'), 'sys_user', ['user_name'], unique=True)
    op.create_table('sys_role_menu',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('menu_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['sys_menu.menu_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.role_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'menu_id')
    )
    op.create_table('sys_user_dept',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('dept_id', sa.BigInteger(), nullable=False),
    sa.Column('is_primary', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['sys_dept.dept_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'dept_id')
    )
    op.create_table('sys_user_role',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.role_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_user_role')
    op.drop_table('sys_user_dept')
    op.drop_table('sys_role_menu')
    op.drop_index(op.f('ix_sys_user_user_name'), table_name='sys_user')
    op.drop_table('sys_user')
    op.drop_table('sys_role')
    op.drop_table('sys_menu')
    op.drop_table('sys_dict_type')
    op.drop_table('sys_dict_data')
    op.drop_table('sys_dept')
    # ### end Alembic commands ###
