"""add sys_config table

Revision ID: a6a5322fd1b6
Revises: e80b847c61f4
Create Date: 2026-05-15 14:26:46.810731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6a5322fd1b6'
down_revision: Union[str, Sequence[str], None] = 'e80b847c61f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_config',
    sa.Column('config_id', sa.BigInteger(), nullable=False, comment='配置ID'),
    sa.Column('config_name', sa.String(length=100), nullable=False, comment='配置名称'),
    sa.Column('config_key', sa.String(length=100), nullable=False, comment='配置键'),
    sa.Column('config_value', sa.Text(), nullable=False, comment='配置值'),
    sa.Column('config_type', sa.String(length=20), nullable=False, comment='配置类型：text/richtext/file'),
    sa.Column('config_group', sa.String(length=50), nullable=False, comment='配置分组'),
    sa.Column('status', sa.String(length=2), nullable=False, comment='状态：1-启用，2-禁用'),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否公开访问'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('create_by', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('config_id'),
    sa.UniqueConstraint('config_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_config')
    # ### end Alembic commands ###
