"""add ai_model table, ai_message parts, provider create_by

Revision ID: bef2b72de182
Revises: 0d45e1d2870d
Create Date: 2026-05-28 09:21:23.873499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bef2b72de182'
down_revision: Union[str, Sequence[str], None] = '0d45e1d2870d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_message', sa.Column('parts', sa.JSON(), nullable=True, comment='结构化消息内容（含图片、文件等）'))
    op.add_column('ai_provider', sa.Column('create_by', sa.String(length=64), nullable=True, comment='创建者'))
    op.alter_column('ai_provider', 'config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='扩展配置（温度、token 限额等）',
               existing_comment='扩展配置（默认模型、温度、token 限额等）',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_provider', 'config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='扩展配置（默认模型、温度、token 限额等）',
               existing_comment='扩展配置（温度、token 限额等）',
               existing_nullable=True)
    op.drop_column('ai_provider', 'create_by')
    op.drop_column('ai_message', 'parts')
    # ### end Alembic commands ###
