"""add ai module tables

Revision ID: e80b847c61f4
Revises: 6957ad20070b
Create Date: 2026-05-04 10:22:44.984598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e80b847c61f4'
down_revision: Union[str, Sequence[str], None] = '6957ad20070b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_provider',
    sa.Column('provider_id', sa.BigInteger(), nullable=False, comment='提供商ID'),
    sa.Column('provider_code', sa.String(length=50), nullable=False, comment='提供商标识：openai / anthropic / deepseek'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='显示名称'),
    sa.Column('api_key', sa.String(length=500), nullable=False, comment='API Key（加密存储）'),
    sa.Column('base_url', sa.String(length=500), nullable=True, comment='API 地址（OpenAI 兼容协议留空用默认）'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('config', sa.JSON(), nullable=True, comment='扩展配置（默认模型、温度、token 限额等）'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('provider_id'),
    sa.UniqueConstraint('provider_code')
    )
    op.create_table('ai_conversation',
    sa.Column('conversation_id', sa.BigInteger(), nullable=False, comment='会话ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='所属用户'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='会话标题'),
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='使用的模型标识'),
    sa.Column('system_prompt', sa.Text(), nullable=True, comment='系统提示词（Agent instructions）'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='状态：0=活跃, 1=归档'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_table('ai_message',
    sa.Column('message_id', sa.BigInteger(), nullable=False, comment='消息ID'),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False, comment='所属会话'),
    sa.Column('parent_message_id', sa.BigInteger(), nullable=True, comment='父消息（工具调用关联链）'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色：user / assistant / system / tool'),
    sa.Column('message_type', sa.String(length=20), nullable=False, comment='类型：text / tool_call / tool_result'),
    sa.Column('content', sa.Text(), nullable=True, comment='消息内容'),
    sa.Column('tokens_input', sa.Integer(), nullable=True, comment='输入 token 数'),
    sa.Column('tokens_output', sa.Integer(), nullable=True, comment='输出 token 数'),
    sa.Column('tool_calls', sa.JSON(), nullable=True, comment='工具调用记录（名称、参数、结果）'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversation.conversation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_message')
    op.drop_table('ai_conversation')
    op.drop_table('ai_provider')
    # ### end Alembic commands ###
