"""add sys_job

Revision ID: ef3d6a37d688
Revises: 6565b01411c3
Create Date: 2026-04-21 11:21:29.480065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef3d6a37d688'
down_revision: Union[str, Sequence[str], None] = '6565b01411c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_job',
    sa.Column('job_id', sa.BigInteger(), nullable=False, comment='任务ID'),
    sa.Column('job_name', sa.String(length=64), nullable=False, comment='任务名称'),
    sa.Column('job_key', sa.String(length=64), nullable=False, comment='任务标识'),
    sa.Column('cron_expression', sa.String(length=64), nullable=True, comment='cron表达式'),
    sa.Column('trigger_type', sa.String(length=10), nullable=False, comment='调度类型：cron-表达式，interval-间隔'),
    sa.Column('interval_value', sa.Integer(), nullable=True, comment='间隔值'),
    sa.Column('interval_unit', sa.String(length=10), nullable=True, comment='间隔单位：seconds/minutes/hours/days'),
    sa.Column('job_args', sa.Text(), nullable=True, comment='任务参数JSON'),
    sa.Column('status', sa.String(length=2), nullable=False, comment='状态：1-启用，2-停用'),
    sa.Column('concurrent', sa.String(length=2), nullable=False, comment='并发策略：1-允许，2-不允许'),
    sa.Column('remark', sa.String(length=256), nullable=True, comment='备注'),
    sa.Column('create_by', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_by', sa.String(length=64), nullable=True, comment='更新者'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('job_key')
    )
    op.create_table('sys_job_log',
    sa.Column('job_log_id', sa.BigInteger(), nullable=False, comment='日志ID'),
    sa.Column('job_id', sa.BigInteger(), nullable=False, comment='任务ID'),
    sa.Column('job_name', sa.String(length=64), nullable=False, comment='任务名称'),
    sa.Column('job_key', sa.String(length=64), nullable=False, comment='任务标识'),
    sa.Column('status', sa.String(length=2), nullable=False, comment='状态：1-成功，2-失败，3-执行中'),
    sa.Column('error_msg', sa.Text(), nullable=True, comment='异常信息'),
    sa.Column('start_time', sa.DateTime(), nullable=False, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='结束时间'),
    sa.Column('duration', sa.Integer(), nullable=True, comment='耗时（毫秒）'),
    sa.PrimaryKeyConstraint('job_log_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_job_log')
    op.drop_table('sys_job')
    # ### end Alembic commands ###
