"""常量模块"""

from app.constants.constants import (
    ADMIN_USERNAME,
    DEFAULT_ACCESS_TOKEN_EXPIRE_MINUTES,
    DEFAULT_PAGE_CURRENT,
    DEFAULT_PAGE_SIZE,
    DEFAULT_REFRESH_TOKEN_EXPIRE_DAYS,
    MENU_TYPE_BUTTON,
    MENU_TYPE_DIRECTORY,
    MENU_TYPE_MENU,
    REDIS_BLACKLIST_PREFIX,
    REDIS_BLACKLIST_TTL,
    STATUS_DISABLED,
    STATUS_ENABLED,
    SUPER_ADMIN_ROLE_CODE,
    SUPER_ADMIN_USERNAME,
    USER_ROLE_CODE,
)
from app.constants.static_routes import CONSTANT_ROUTES

__all__ = [
    # 应用常量
    "ADMIN_USERNAME",
    "DEFAULT_ACCESS_TOKEN_EXPIRE_MINUTES",
    "DEFAULT_PAGE_CURRENT",
    "DEFAULT_PAGE_SIZE",
    "DEFAULT_REFRESH_TOKEN_EXPIRE_DAYS",
    "MENU_TYPE_BUTTON",
    "MENU_TYPE_DIRECTORY",
    "MENU_TYPE_MENU",
    "REDIS_BLACKLIST_PREFIX",
    "REDIS_BLACKLIST_TTL",
    "STATUS_DISABLED",
    "STATUS_ENABLED",
    "SUPER_ADMIN_ROLE_CODE",
    "SUPER_ADMIN_USERNAME",
    "USER_ROLE_CODE",
    # 路由常量
    "CONSTANT_ROUTES",
]
